name: .NET Core

on:
  push:
    branches: [ develop ]
    
env:
  AZURE_WEBAPP_PACKAGE_PATH: '.' 

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Set DbPassword
      run: dotnet user-secrets set "DbPassword" ${{ secrets.DBPASSWORD }}
    - name: Install dependencies
      run: dotnet tool install --global dotnet-ef
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
    - name: Update Database
      run: dotnet ef database update --project AdvancedAnalysisDesign
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        # Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # optional
        # Name of the Azure Web App
        app-name: BinaryBeast
        # Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' # optional, default is .
        # Enter an existing Slot other than the Production slot
        #slot-name: # optional, default is production
